# Generated by Django 2.2.5 on 2019-12-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondmall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.ImageField(upload_to='goods_img'),
        ),
    ]
